package CorbaApp2;


/**
* CorbaApp2/_ShoppingCartImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaApp2.idl
* sobota, 24 czerwca 2017 13:56:40 CEST
*/

public abstract class _ShoppingCartImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements CorbaApp2.ShoppingCart, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ShoppingCartImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_customer", new java.lang.Integer (0));
    _methods.put ("_set_customer", new java.lang.Integer (1));
    _methods.put ("_get_orders", new java.lang.Integer (2));
    _methods.put ("addToCart", new java.lang.Integer (3));
    _methods.put ("removeFromCart", new java.lang.Integer (4));
    _methods.put ("sumItUp", new java.lang.Integer (5));
    _methods.put ("clear", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CorbaApp2/ShoppingCart/_get_customer
       {
         CorbaApp2.Customer $result = null;
         $result = this.customer ();
         out = $rh.createReply();
         CorbaApp2.CustomerHelper.write (out, $result);
         break;
       }

       case 1:  // CorbaApp2/ShoppingCart/_set_customer
       {
         CorbaApp2.Customer newCustomer = CorbaApp2.CustomerHelper.read (in);
         this.customer (newCustomer);
         out = $rh.createReply();
         break;
       }

       case 2:  // CorbaApp2/ShoppingCart/_get_orders
       {
         CorbaApp2.OrderItem $result[] = null;
         $result = this.orders ();
         out = $rh.createReply();
         CorbaApp2.OrdersHelper.write (out, $result);
         break;
       }

       case 3:  // CorbaApp2/ShoppingCart/addToCart
       {
         try {
           CorbaApp2.Product product = CorbaApp2.ProductHelper.read (in);
           int qty = in.read_long ();
           CorbaApp2.Customer cust = CorbaApp2.CustomerHelper.read (in);
           this.addToCart (product, qty, cust);
           out = $rh.createReply();
         } catch (CorbaApp2.StockIsEmpty $ex) {
           out = $rh.createExceptionReply ();
           CorbaApp2.StockIsEmptyHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // CorbaApp2/ShoppingCart/removeFromCart
       {
         try {
           CorbaApp2.Product product = CorbaApp2.ProductHelper.read (in);
           int qty = in.read_long ();
           CorbaApp2.Customer cust = CorbaApp2.CustomerHelper.read (in);
           this.removeFromCart (product, qty, cust);
           out = $rh.createReply();
         } catch (CorbaApp2.NoEnoughItems $ex) {
           out = $rh.createExceptionReply ();
           CorbaApp2.NoEnoughItemsHelper.write (out, $ex);
         }
         break;
       }

       case 5:  // CorbaApp2/ShoppingCart/sumItUp
       {
         CorbaApp2.Customer cust = CorbaApp2.CustomerHelper.read (in);
         String $result = null;
         $result = this.sumItUp (cust);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 6:  // CorbaApp2/ShoppingCart/clear
       {
         CorbaApp2.Customer cust = CorbaApp2.CustomerHelper.read (in);
         this.clear (cust);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CorbaApp2/ShoppingCart:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ShoppingCartImplBase
