package CorbaApp2;

/**
* CorbaApp2/CustomerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaApp2.idl
* sobota, 24 czerwca 2017 13:56:40 CEST
*/

public final class CustomerHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaApp2.Customer value = null;

  public CustomerHolder ()
  {
  }

  public CustomerHolder (CorbaApp2.Customer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaApp2.CustomerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaApp2.CustomerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaApp2.CustomerHelper.type ();
  }

}
