package CorbaApp2;


/**
* CorbaApp2/Customer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaApp2.idl
* sobota, 24 czerwca 2017 13:56:40 CEST
*/

public final class Customer implements org.omg.CORBA.portable.IDLEntity
{
  public int customerId = (int)0;
  public String fullName = null;

  public Customer ()
  {
  } // ctor

  public Customer (int _customerId, String _fullName)
  {
    customerId = _customerId;
    fullName = _fullName;
  } // ctor

} // class Customer
