package CorbaApp2;


/**
* CorbaApp2/NoEnoughItems.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaApp2.idl
* sobota, 24 czerwca 2017 13:56:40 CEST
*/

public final class NoEnoughItems extends org.omg.CORBA.UserException
{
  public String reason = null;

  public NoEnoughItems ()
  {
    super(NoEnoughItemsHelper.id());
  } // ctor

  public NoEnoughItems (String _reason)
  {
    super(NoEnoughItemsHelper.id());
    reason = _reason;
  } // ctor


  public NoEnoughItems (String $reason, String _reason)
  {
    super(NoEnoughItemsHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class NoEnoughItems
