package CorbaApp2;


/**
* CorbaApp2/OrderItem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaApp2.idl
* sobota, 24 czerwca 2017 13:56:40 CEST
*/

public final class OrderItem implements org.omg.CORBA.portable.IDLEntity
{
  public double price = (double)0;
  public int quantity = (int)0;
  public CorbaApp2.Product product = null;

  public OrderItem ()
  {
  } // ctor

  public OrderItem (double _price, int _quantity, CorbaApp2.Product _product)
  {
    price = _price;
    quantity = _quantity;
    product = _product;
  } // ctor

} // class OrderItem
