package CorbaApp2;


/**
* CorbaApp2/OrderItemHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaApp2.idl
* sobota, 24 czerwca 2017 13:56:40 CEST
*/

abstract public class OrderItemHelper
{
  private static String  _id = "IDL:CorbaApp2/OrderItem:1.0";

  public static void insert (org.omg.CORBA.Any a, CorbaApp2.OrderItem that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CorbaApp2.OrderItem extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[0] = new org.omg.CORBA.StructMember (
            "price",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "quantity",
            _tcOf_members0,
            null);
          _tcOf_members0 = CorbaApp2.ProductHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "product",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (CorbaApp2.OrderItemHelper.id (), "OrderItem", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CorbaApp2.OrderItem read (org.omg.CORBA.portable.InputStream istream)
  {
    CorbaApp2.OrderItem value = new CorbaApp2.OrderItem ();
    value.price = istream.read_double ();
    value.quantity = istream.read_long ();
    value.product = CorbaApp2.ProductHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CorbaApp2.OrderItem value)
  {
    ostream.write_double (value.price);
    ostream.write_long (value.quantity);
    CorbaApp2.ProductHelper.write (ostream, value.product);
  }

}
