package CorbaApp2;


/**
* CorbaApp2/Product.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaApp2.idl
* sobota, 24 czerwca 2017 13:56:40 CEST
*/

public final class Product implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public int version = (int)0;
  public int stock = (int)0;
  public double price = (double)0;

  public Product ()
  {
  } // ctor

  public Product (String _name, int _version, int _stock, double _price)
  {
    name = _name;
    version = _version;
    stock = _stock;
    price = _price;
  } // ctor

} // class Product
