package CorbaApp2;


/**
* CorbaApp2/ShoppingCartOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaApp2.idl
* sobota, 24 czerwca 2017 13:56:40 CEST
*/

public interface ShoppingCartOperations 
{
  CorbaApp2.Customer customer ();
  void customer (CorbaApp2.Customer newCustomer);
  CorbaApp2.OrderItem[] orders ();
  void addToCart (CorbaApp2.Product product, int qty, CorbaApp2.Customer cust) throws CorbaApp2.StockIsEmpty;
  void removeFromCart (CorbaApp2.Product product, int qty, CorbaApp2.Customer cust) throws CorbaApp2.NoEnoughItems;
  String sumItUp (CorbaApp2.Customer cust);
  void clear (CorbaApp2.Customer cust);
} // interface ShoppingCartOperations
