package CorbaApp2;


/**
* CorbaApp2/ShoppingCart.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaApp2.idl
* sobota, 24 czerwca 2017 13:56:40 CEST
*/

public interface ShoppingCart extends ShoppingCartOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ShoppingCart
