package CorbaApp2;

/**
* CorbaApp2/StockIsEmptyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaApp2.idl
* sobota, 24 czerwca 2017 13:56:40 CEST
*/

public final class StockIsEmptyHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaApp2.StockIsEmpty value = null;

  public StockIsEmptyHolder ()
  {
  }

  public StockIsEmptyHolder (CorbaApp2.StockIsEmpty initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaApp2.StockIsEmptyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaApp2.StockIsEmptyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaApp2.StockIsEmptyHelper.type ();
  }

}
